---
latitude: 45.43666
longitude: 12.33624
map_zoom: 12
name: Apartments San Marco Square with Terrace
email: steffan@traveltripper.io
phone_number: 001-111-1111
address:
  street1: San Marco 5204
  street2: ''
  state: ''
  city: Venice
  country: 
  zip_code: ''
_hotel_id: APA836
_portal_id: required-but-empty
_ttweb_plugins_version: v2
_root_path: http://rtexpress-qa.ttaws.com/rt/.
